include: package:flutter_lints/flutter.yaml

# Additional rules and customizations
linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - unnecessary_const
    - unnecessary_new
    - use_key_in_widget_constructors