name: offline_chat_app
description: A Flutter offline chat app using Gemma 3N model
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_gemma: ^0.10.0
  provider: ^6.0.5
  http: ^1.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  flutter_phone_direct_caller: ^2.1.1
  flutter_markdown: ^0.6.18
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/data/emergency_numbers_all_countries.json
    - assets/thedoctor.png
    - .env